/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 island.glb 
Author: nimzu (https://sketchfab.com/nimzuk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/foxs-islands-163b68e09fcc47618450150be7785907
Title: Fox's islands
*/

import { useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import React, { useRef } from "react";
import { a } from "@react-spring/three";

import islandScene from "../assets/3d/island.glb";

const Island = (props) => {
  const islandRef = useRef();
  const { nodes, materials } = useGLTF(islandScene);
  return (
    <a.group ref={islandRef} {...props} dispose={null}>
      <mesh
        geometry={nodes.pCube11_rocks1_0.geometry}
        material={materials.PaletteMaterial001}
      />
      <instancedMesh
        args={[
          nodes.polySurface944_tree_body_0.geometry,
          materials.PaletteMaterial001,
          8,
        ]}
        instanceMatrix={nodes.polySurface944_tree_body_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.polySurface945_tree1_0.geometry,
          materials.PaletteMaterial001,
          5,
        ]}
        instanceMatrix={nodes.polySurface945_tree1_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.polySurface946_tree2_0.geometry,
          materials.PaletteMaterial001,
          5,
        ]}
        instanceMatrix={nodes.polySurface946_tree2_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.polySurface947_tree1_0.geometry,
          materials.PaletteMaterial001,
          5,
        ]}
        instanceMatrix={nodes.polySurface947_tree1_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.polySurface948_tree_body_0.geometry,
          materials.PaletteMaterial001,
          8,
        ]}
        instanceMatrix={nodes.polySurface948_tree_body_0.instanceMatrix}
      />
      <instancedMesh
        args={[
          nodes.polySurface949_tree_body_0.geometry,
          materials.PaletteMaterial001,
          8,
        ]}
        instanceMatrix={nodes.polySurface949_tree_body_0.instanceMatrix}
      />
    </a.group>
  );
};

export default Island;
