/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 sky.glb 
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-in-the-cloud-b270497defe24f9cb497b9a075eeb28f
Title: FREE - SkyBox In The Cloud
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";
import skyScene from "../assets/3d/sky.glb";

const Sky = (props) => {
  const skyref = useRef();
  const { nodes, materials } = useGLTF(skyScene);
  return (
    <a.group ref={skyref} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Sphere__0.geometry}
          material={materials["Scene_-_Root"]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={50000}
        />
      </group>
    </a.group>
  );
};

useGLTF.preload("/sky.glb");

export default Sky;
